### ISSUE TITLE
Miss merged PR

### ISSUE THREAD

**Issue by hfmrow** [gotk3/gotk3#830]
**Describe the bug**
#826 This PR should not have been merged !!! It contains "bad / misplaced" implementation of **binding_dup_source** and **binding_dup_target**
```go
// Retrieves the GObject instance used as the source of the binding
func (v *Binding) GetSource() *Object {
// 	obj := C.g_binding_get_source(v.native())
	obj := C.g_binding_dup_source(v.native())
	if obj == nil {
		return nil
	}
	return wrapObject(unsafe.Pointer(obj))
}
```
that will create compilation error.

Hi, ~~@MJacred~~ @andre-hub, You have merged a bad pull request, can you reverse it please.
The #828 is the correct implementation https://github.com/gotk3/gotk3/commit/73371d7038f2874484dbc01d90ae4081f3504e3b

**Comment by MJacred** [comment]
@hfmrow: You got the wrong person.

@andre-hub: hfmrow seems to have found an issue with PR #826

**Comment by hfmrow** [comment]
@MJacred yes sorry,

My request is for @andre-hub...
I'll publish a pr that corrects previous merge of #826.

**Comment by andre-hub** [comment]
do we need an additional branch so that it does not cause problems with the others?

Whereby the CI (github actions) should check this. https://github.com/gotk3/gotk3/runs/3518382807?check_suite_focus=true

Unfortunately, there has no error message

But okay, it was my mistake that I had misinterpreted  "... based ..." that.

**Comment by hfmrow** [comment]
> do we need an additional branch so that it does not cause problems with the others
No, i don't think.

I've done #828 PR in right way (conforming to gotk3 rules about version restrictions), using #826 information.
All operations are detailed into #826 and in #828, including the issue with the github 'checker' configuration (#828).
` glib/gbinding_since_2_68.go:14:9: could not determine kind of name for C.g_binding_dup_source`
`glib/gbinding_since_2_68.go:23:9: could not determine kind of name for C.g_binding_dup_target`
depend on glib version used, all explanation are detailed in #828.

Thank for your reactivity.

**Comment by sqp** [comment]
I just finished to test build with and without tag gtk_2_66 and it seem ok for me.

**Comment by hfmrow** [comment]
@sqp 
I am on Ubuntu 20.04.1 with glib2.64.6 only, if I don't use `-tags gtk_2_66` I have a compilation error.
What version of glib are you working with? if it's> = 2.66 this behavior is normal.

**Comment by sqp** [comment]
My versions on manjaro are close to upstream.
glib2    2.68.4-1
gtk3     3.24.30-2

**Comment by sqp** [comment]
My versions on manjaro are close to upstream.
```
glib2    2.68.4-1
gtk3     3.24.30-2
```

**Comment by hfmrow** [comment]
Then we're ok ^^

**Comment by hfmrow** [comment]
hi @sqp.
After reflection, if you use the -tags "gtk_2_66" with your glib version (2.68), logically you should have a "Gtk Warning deprecated" which concerns `C.g_binding_dup_source`, `C.g_binding_dup_target`.

Could you confirm whether it's yes or not? if it's not, it's an issue because i've made tag restriction to avoid using the new implementation with glib version <2.68

**Comment by sqp** [comment]
Yes I have those warnings with the tag (since I updated to confirm and help test/fix when I saw messages about that problem).

The real problem is that those warnings seem blocking for windows devs:
- They'd better not install bleeding edge versions of those API (or wait 2/3 months after the release).
- We'd better warn them fast the next time something blocking for them happens.

**Comment by sqp** [comment]
And as this is a breaking change, we'd better push a new version for it.

**Comment by hfmrow** [comment]
> The real problem is that those warnings seem blocking for windows devs:
     * They'd better not install bleeding edge versions of those API (or wait 2/3 months after the release).
     * We'd better warn them fast the next time something blocking for them happens.

I'm not sure, but I think Windows developers have the same ways for the version restriction limit and the final behavior doesn't change compared to Linux/Darwin developers.

An announcement was made in the 'CHANGE.md' file to prevent any disappointment.
