### ISSUE TITLE
Cannot build on ubuntu 18.04

### ISSUE THREAD

**Issue by homax** [gotk3/gotk3#402]
Hi, I have a problem while compiling the app.

```In file included from /usr/include/x86_64-linux-gnu/sys/cdefs.h:427:0,
                 from /usr/include/glib-2.0/features.h:378,
                 from /usr/include/glib-2.0/stdlib/stdlib.h:24,
                 from /usr/include/glib-2.0/stdlib.h:10,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/cairo/antialias.go:3:
/usr/include/glib-2.0/bits/wordsize.h:1:2: error: #error "This file must be written based on the data type sizes of the target"
 #error "This file must be written based on the data type sizes of the target"
  ^~~~~
In file included from /usr/include/glib-2.0/features.h:378:0,
                 from /usr/include/glib-2.0/stdlib/stdlib.h:24,
                 from /usr/include/glib-2.0/stdlib.h:10,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/cairo/antialias.go:3:
/usr/include/x86_64-linux-gnu/sys/cdefs.h:467:49: error: missing binary operator before token "("
 #if __GNUC_PREREQ (4,8) || __glibc_clang_prereq (3,5)
                                                 ^
In file included from /usr/include/glib-2.0/string/endian.h:36:0,
                 from /usr/include/glib-2.0/endian.h:1,
                 from /usr/include/glib-2.0/bits/waitstatus.h:64,
                 from /usr/include/glib-2.0/stdlib/stdlib.h:42,
                 from /usr/include/glib-2.0/stdlib.h:10,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/cairo/antialias.go:3:
/usr/include/glib-2.0/bits/endian.h:13:2: error: #error Machine byte order unknown.
 #error Machine byte order unknown.
  ^~~~~
In file included from /usr/include/glib-2.0/bits/types.h:27:0,
                 from /usr/include/glib-2.0/bits/byteswap.h:27,
                 from /usr/include/glib-2.0/string/endian.h:60,
                 from /usr/include/glib-2.0/endian.h:1,
                 from /usr/include/glib-2.0/bits/waitstatus.h:64,
                 from /usr/include/glib-2.0/stdlib/stdlib.h:42,
                 from /usr/include/glib-2.0/stdlib.h:10,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/cairo/antialias.go:3:
/usr/include/glib-2.0/bits/wordsize.h:1:2: error: #error "This file must be written based on the data type sizes of the target"
 #error "This file must be written based on the data type sizes of the target"
  ^~~~~
In file included from /usr/include/glib-2.0/bits/byteswap.h:27:0,
                 from /usr/include/glib-2.0/string/endian.h:60,
                 from /usr/include/glib-2.0/endian.h:1,
                 from /usr/include/glib-2.0/bits/waitstatus.h:64,
                 from /usr/include/glib-2.0/stdlib/stdlib.h:42,
                 from /usr/include/glib-2.0/stdlib.h:10,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/cairo/antialias.go:3:
/usr/include/glib-2.0/bits/types.h:119:3: error: #error 
 # error
   ^~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/select.h:123:0,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:197,
                 from /usr/include/glib-2.0/stdlib/stdlib.h:314,
                 from /usr/include/glib-2.0/stdlib.h:10,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/cairo/antialias.go:3:
/usr/include/glib-2.0/bits/select2.h:1:10: fatal error: ../../misc/bits/select2.h: No such file or directory
 #include "../../misc/bits/select2.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
# github.com/gotk3/gotk3/gdk
In file included from /usr/include/x86_64-linux-gnu/sys/cdefs.h:427:0,
                 from /usr/include/glib-2.0/features.h:378,
                 from /usr/include/glib-2.0/limits.h:25,
                 from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:11,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/gdk/gdk.go:21:
/usr/include/glib-2.0/bits/wordsize.h:1:2: error: #error "This file must be written based on the data type sizes of the target"
 #error "This file must be written based on the data type sizes of the target"
  ^~~~~
In file included from /usr/include/glib-2.0/features.h:378:0,
                 from /usr/include/glib-2.0/limits.h:25,
                 from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:11,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/gdk/gdk.go:21:
/usr/include/x86_64-linux-gnu/sys/cdefs.h:467:49: error: missing binary operator before token "("
 #if __GNUC_PREREQ (4,8) || __glibc_clang_prereq (3,5)
                                                 ^
In file included from /usr/include/glib-2.0/bits/types.h:27:0,
                 from /usr/include/glib-2.0/time/time.h:55,
                 from /usr/include/glib-2.0/time.h:5,
                 from /usr/include/glib-2.0/glib/gtypes.h:35,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/gdk/gdk.go:21:
/usr/include/glib-2.0/bits/wordsize.h:1:2: error: #error "This file must be written based on the data type sizes of the target"
 #error "This file must be written based on the data type sizes of the target"
  ^~~~~
In file included from /usr/include/glib-2.0/time/time.h:55:0,
                 from /usr/include/glib-2.0/time.h:5,
                 from /usr/include/glib-2.0/glib/gtypes.h:35,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/gdk/gdk.go:21:
/usr/include/glib-2.0/bits/types.h:119:3: error: #error 
 # error
   ^~~~~
In file included from /usr/include/glib-2.0/string/endian.h:36:0,
                 from /usr/include/glib-2.0/endian.h:1,
                 from /usr/include/glib-2.0/bits/waitstatus.h:64,
                 from /usr/include/glib-2.0/stdlib/stdlib.h:42,
                 from /usr/include/glib-2.0/stdlib.h:10,
                 from /usr/include/glib-2.0/glib/gutils.h:306,
                 from /usr/include/glib-2.0/glib/gthread.h:34,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/gdk/gdk.go:21:
/usr/include/glib-2.0/bits/endian.h:13:2: error: #error Machine byte order unknown.
 #error Machine byte order unknown.
  ^~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/select.h:123:0,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:197,
                 from /usr/include/glib-2.0/stdlib/stdlib.h:314,
                 from /usr/include/glib-2.0/stdlib.h:10,
                 from /usr/include/glib-2.0/glib/gutils.h:306,
                 from /usr/include/glib-2.0/glib/gthread.h:34,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from ../../../go/pkg/mod/github.com/gotk3/gotk3@v0.0.0-20190620081259-6dcdf9e5c51e/gdk/gdk.go:21:
/usr/include/glib-2.0/bits/select2.h:1:10: fatal error: ../../misc/bits/select2.h: No such file or directory
 #include "../../misc/bits/select2.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Am I missing something? I installed `sudo apt-get install libgtk-3-dev libcairo2-dev libglib2.0-dev`, should install something else?

**Comment by hfmrow** [comment]
Hi, you get that after a:
`
go get github.com/gotk3/gotk3/gtk
` ?

**Comment by homaxweb** [comment]
Difficult to say. I get it after every attempt to run tests, build and after `go get github.com/gotk3/gotk3/gtk` as well.

**Comment by hfmrow** [comment]
I never running tests ...
Try just :
`go get github.com/gotk3/gotk3/gtk`
Normally, it automatically compiled for gtk3.22 and you would don't get any error
Next, get a source from example repository, compile and run it.
i.e: https://github.com/gotk3/gotk3-examples/tree/master/gtk-examples/treeview
get it and put it in your "Golang" workspace directory
and, in this local directory type:
`go run treeview.go `
after few seconds, you must show a window with treeview.

**Comment by wrycode** [comment]
@homaxweb are you still having this problem?

**Comment by homaxweb** [comment]
yes and I'm pretty sure that the problem might be caused by inconsistent versions of system libraries. I didn't manage to figure out what exactly was wrong, but as a work around, I used a docker container to install gtk3 and everything else one more time. It solved my problem. Besides it's more convenient to use.
