### ISSUE TITLE
Unable to build when importing gotk3/gotk3

### ISSUE THREAD

**Issue by mlb5000** [gotk3/gotk3#116]
I have `libgtk-3-dev` version 3.12.2 installed on Ubuntu 14.04, but when I run `go build main.go` I get the following output:

```
# github.com/gotk3/gotk3/gtk
could not determine kind of name for C.gtk_application_get_actions_for_accel
could not determine kind of name for C.gtk_application_get_menu_by_id
could not determine kind of name for C.gtk_application_prefers_app_menu
```

Do you have any suggestions?

**Comment by mlb5000** [comment]
And if I build using `go build -tags gtk_3_12 main.go` I get the following

```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-587755410/000009.o: In function `removeClosure':
/tmp/go-build135241220/github.com/gotk3/gotk3/glib/_obj/_cgo_export.c:10: multiple definition of `removeClosure'
/tmp/go-link-587755410/000001.o:/tmp/go-build135241220/github.com/conformal/gotk3/glib/_obj/_cgo_export.c:10: first defined here
/tmp/go-link-587755410/000009.o: In function `goMarshal':
/tmp/go-build135241220/github.com/gotk3/gotk3/glib/_obj/_cgo_export.c:23: multiple definition of `goMarshal'
/tmp/go-link-587755410/000001.o:/tmp/go-build135241220/github.com/conformal/gotk3/glib/_obj/_cgo_export.c:23: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by Soreil** [comment]
Your first error is because all those GTK features are from GTK 3.14. The second is more interesting, for good measure, which Go version are you on?

**Comment by mlb5000** [comment]
@Soreil I was on Go 1.6, but even after I got it to build from a clean Ubuntu 14.04 build with `-tags gtk_3_10` it wouldn't run due to `panic: runtime error: cgo argument has Go pointer to Go pointer`. Apparently Go 1.6 is strict about passing Go pointers to C. I downgraded to 1.5 and now all is well.

The other issue (I believe) is that the library I was initially trying to use (Webloop) still had a reference to this library's old location under `conformal`, causing two versions of the gotk3 library to be built and linked.

**Comment by Soreil** [comment]
It should work fine on Go 1.6 with the new pointer sharong rules, I'll give it a test on my end.
Also, there is an environment variable you can set to disable the new rules, this will let you use Go 1.6 in your case.

**Comment by mlb5000** [comment]
@Soreil that's good to know. The Go version wasn't all that important in this particular instance so it wasn't too big a deal.

**Comment by rafaelcn** [comment]
So `Go 1.6` won't work with gotk3 because of the new language rules?

**Comment by Soreil** [comment]
It works just fine on my Linux/AMD64 install using Go 1.6 with the new pointer rules enabled, as is the default. I'm curious which errors people are having with it.

**Comment by andre-hub** [comment]
the problem is, we have tags for regulation the versions, the old version support for gtk has bugs with the newest versions auf go. the constellation very old version of gtk and new version of go is rarely or not?

e.g. in debian have we go 1.3 and gtk 3.14

**Comment by rafaelcn** [comment]
Working just fine here with `go1.6 linux/amd64` with the default rules enabled.

**Comment by jmoiron** [comment]
I can build against gotk3 but I get this error when I try to run `go test` in `gotk3/glib`

**Comment by jmoiron** [comment]
Scratch what I said in my previous comment, I think the issue here is that somehow both the `github.com/gotk3/gotk3` and the conformal paths are being imported into the original user's.  This is evident in the original problem report:

> /tmp/go-build135241220/**github.com/gotk3/gotk3/glib**/_obj/_cgo_export.c:23: multiple definition of `goMarshal'
/tmp/go-link-587755410/000001.o:/tmp/go-build135241220/**github.com/conformal/gotk3/glib**/_obj/_cgo_export.c:23: first defined here

This is in fact the same error as I encountered, because I was doing development on gotk3 from a separate path (my fork path `github.com/jmoiron/gotk3`) and gotk3's test files use separate test packages and actually import the full path of the dependent libraries.  As an example, test files in `gotk3/glib` use `package glib_test` and import `github.com/gotk3/gotk3/glib`, meaning when you build them from a different path you will get your "local" `glib` package and the one at `github.com/gotk3/gotk3/glib`the same C symbols linked in twice and see the error above.

I'm pretty convinced this isn't a bug.

**Comment by paultag** [comment]
@jmoiron Confirmed! I tried that fix and it's happy. Seems real bad the imports in `gotk` are importing the old name. I'll send a PR.

**Comment by paultag** [comment]
Yikes. Nevermind! I had a clone of the old repo, and the import names on the old one are the old path. This is gnarly. I won't PR since it seems like that was done intentionally.
